import type { ObjectKind, TypeSpec } from './types';

/**
 * Starting dimensions come from the OPTION 2 concept drawing. Every min* is
 * user-editable at runtime via the side panel; these are only the seed values.
 *
 * Bay depth 6.30 m = 1.70 m seating/safety strip + 4.60 m hitting enclosure.
 */
export const CATALOG: Record<ObjectKind, TypeSpec> = {
  'social-bay': {
    kind: 'social-bay',
    label: 'Social bay',
    fill: '#d9ece8',
    stroke: '#0f6e56',
    text: '#123f33',
    minW: 4.5,
    minD: 6.3,
    defaultW: 4.5,
    defaultD: 6.3,
    defaultSeatingDepth: 1.7,
    capacity: 6,
    requiresClearance: true,
  },
  'ai-bay': {
    kind: 'ai-bay',
    label: 'AI bay',
    fill: '#dbe9f5',
    stroke: '#1d6fa5',
    text: '#123c56',
    minW: 3.7,
    minD: 6.3,
    defaultW: 3.7,
    defaultD: 6.3,
    defaultSeatingDepth: 1.7,
    capacity: 4,
    requiresClearance: true,
  },
  'vip-bay': {
    kind: 'vip-bay',
    label: 'VIP bay',
    fill: '#e8e2f2',
    stroke: '#6a4fa3',
    text: '#33265c',
    // 5.555, not the 5.56 the concept quotes: 5.56 is that number rounded to
    // 2 dp, and the traced VIP is exactly 5555 mm. Using the rounded figure as
    // the minimum made the untouched seed VIP report itself as undersized.
    // Widening the seed instead is not an option — it would push the bay 5 mm
    // into the service band and invent an overlap.
    minW: 5.555,
    minD: 6.3,
    defaultW: 5.555,
    defaultD: 6.78,
    defaultSeatingDepth: 2.18,
    capacity: 8,
    requiresClearance: true,
  },
  'putting-green': {
    kind: 'putting-green',
    label: 'Putting green',
    fill: '#e7f2e4',
    stroke: '#005a32',
    text: '#26421f',
    minW: 4,
    minD: 1.8,
    defaultW: 9.6,
    defaultD: 2.4,
    capacity: 4,
    // Not a swing hazard, and in the concept it sits close to the glazing and
    // the event floor by design.
    requiresClearance: false,
  },
  'event-floor': {
    kind: 'event-floor',
    label: 'Event floor',
    fill: '#efedfa',
    stroke: '#534ab7',
    text: '#2d2a55',
    minW: 4,
    minD: 3,
    defaultW: 9.3,
    defaultD: 3.0,
    capacity: 0,
    // The aisle between the event floor and the bay row is the concept's
    // circulation route, not a clearance violation.
    requiresClearance: false,
  },
  bar: {
    kind: 'bar',
    label: 'Bar',
    fill: '#f6e6d8',
    stroke: '#a5642a',
    text: '#5a3413',
    minW: 3,
    minD: 1.2,
    defaultW: 6.765,
    defaultD: 2.75,
    capacity: 0,
    requiresClearance: false,
  },
  lounge: {
    kind: 'lounge',
    label: 'Lounge',
    fill: '#fbeef2',
    stroke: '#a8446a',
    text: '#5c2237',
    minW: 3,
    minD: 2,
    defaultW: 7.15,
    defaultD: 2.567,
    capacity: 0,
    requiresClearance: false,
  },
  lockers: {
    kind: 'lockers',
    label: 'Lockers / merch',
    fill: '#eeedea',
    stroke: '#6f6d66',
    text: '#3d3c38',
    minW: 1,
    minD: 0.6,
    defaultW: 1.385,
    defaultD: 6.2,
    capacity: 0,
    requiresClearance: false,
  },
  pantry: {
    kind: 'pantry',
    label: 'Pantry',
    fill: '#eceae5',
    stroke: '#7a776e',
    text: '#43413b',
    minW: 1.2,
    minD: 1.2,
    defaultW: 1.842,
    defaultD: 3.05,
    capacity: 0,
    requiresClearance: false,
  },
  'service-band': {
    kind: 'service-band',
    label: 'Service band',
    fill: '#f2f1ed',
    stroke: '#8a887f',
    text: '#4a4842',
    minW: 0.6,
    minD: 2,
    defaultW: 0.8,
    defaultD: 10.325,
    capacity: 0,
    requiresClearance: false,
  },
  store: {
    kind: 'store',
    label: 'Store',
    fill: '#e4e3de',
    stroke: '#75736c',
    text: '#3d3c38',
    minW: 1.5,
    minD: 1.5,
    defaultW: 4.47,
    defaultD: 3.542,
    capacity: 0,
    requiresClearance: false,
  },
  'cart-pillar': {
    kind: 'cart-pillar',
    label: 'Cart / pillar feature',
    fill: '#f7efdc',
    stroke: '#b08329',
    text: '#5d4413',
    minW: 2,
    minD: 1.4,
    // A golf cart is about 2.4 m long and 1.2 m wide; the footprint here is the
    // front half that emerges from the column, plus standing room around it.
    defaultW: 2.6,
    defaultD: 1.7,
    capacity: 0,
    requiresClearance: false,
  },
  generic: {
    kind: 'generic',
    label: 'Rectangle',
    fill: '#eceef0',
    stroke: '#6b7280',
    text: '#374151',
    minW: 0.5,
    minD: 0.5,
    defaultW: 3,
    defaultD: 2,
    capacity: 0,
    requiresClearance: false,
  },
};

export const CATALOG_ORDER: ObjectKind[] = [
  'social-bay',
  'ai-bay',
  'vip-bay',
  'putting-green',
  'event-floor',
  'bar',
  'lounge',
  'lockers',
  'pantry',
  'service-band',
  'store',
  'cart-pillar',
  'generic',
];

export const BAY_KINDS: ObjectKind[] = ['social-bay', 'ai-bay', 'vip-bay'];

export const isBay = (k: ObjectKind) => BAY_KINDS.includes(k);
